version: "1"
services:
  - type: web
    name: MOTHOR
    runtime: python
    repo: https://github.com/mrparihar08/MOTHOR
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app.app:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        value: change-me
      - key: ML_API_BASE
        value: https://mother-8599.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: vitya-database
          property: connectionString

  - type: web
    name: vitya-ai-ml
    runtime: python
    repo: https://github.com/mrparihar08/MOTHER
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app.app:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vitya-database
          property: connectionString

  - type: web
    name: vitya-ai-frontend
    runtime: static
    repo: https://github.com/mrparihar08/MOTHER
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mother-8599.onrender.com   
