from __future__ import annotations

import collections
import collections.abc
import sys
from pathlib import Path

# Forward compatibility fix for python-pptx / collections on Python 3.10+
for name in ("Container", "Mapping", "MutableMapping", "Sequence", "MutableSequence", "Iterable", "Callable"):
    if not hasattr(collections, name) and hasattr(collections.abc, name):
        setattr(collections, name, getattr(collections.abc, name))

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE


def create_master_template(output_path: str = "./templates/base_template.pptx") -> str:
    """
    Generates a professional 16:9 widescreen Master PowerPoint Template (.pptx)
    with pre-designed layouts, headers, footers, logo placeholders, and color schemes.
    """
    out_file = Path(output_path).resolve()
    out_file.parent.mkdir(parents=True, exist_ok=True)

    prs = Presentation()
    # 16:9 Widescreen dimensions
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Theme Colors
    COLOR_PRIMARY_DARK = RGBColor(15, 23, 42)    # Slate 900
    COLOR_TEAL_ACCENT = RGBColor(13, 148, 136)   # Teal 600
    COLOR_INDIGO_ACCENT = RGBColor(99, 102, 241) # Indigo 500
    COLOR_LIGHT_BG = RGBColor(248, 250, 252)     # Slate 50
    COLOR_BORDER = RGBColor(226, 232, 240)       # Slate 200
    COLOR_TEXT_DARK = RGBColor(15, 23, 42)       # Slate 900
    COLOR_TEXT_MUTED = RGBColor(100, 116, 139)   # Slate 500
    COLOR_TEXT_LIGHT = RGBColor(241, 245, 249)   # Slate 100

    # -------------------------------------------------------------------------
    # Layout 0: Cover / Title Slide Master
    # -------------------------------------------------------------------------
    slide_layout_0 = prs.slide_layouts[0]
    slide_0 = prs.slides.add_slide(slide_layout_0)

    # Fill background
    bg = slide_0.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(7.5))
    bg.fill.solid()
    bg.fill.fore_color.rgb = COLOR_PRIMARY_DARK
    bg.line.fill.background()

    # Left decorative vertical accent bar
    accent_bar = slide_0.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0.8), Inches(1.8), Inches(0.12), Inches(4.0))
    accent_bar.fill.solid()
    accent_bar.fill.fore_color.rgb = COLOR_TEAL_ACCENT
    accent_bar.line.fill.background()

    # Brand Logo / Header Badge
    logo_box = slide_0.shapes.add_textbox(Inches(0.8), Inches(0.8), Inches(4.0), Inches(0.6))
    tf_logo = logo_box.text_frame
    tf_logo.word_wrap = True
    p_logo = tf_logo.paragraphs[0]
    p_logo.text = "MOTHER AI"
    p_logo.font.size = Pt(14)
    p_logo.font.bold = True
    p_logo.font.color.rgb = COLOR_TEAL_ACCENT

    # Title Placeholder Textbox
    title_box = slide_0.shapes.add_textbox(Inches(1.2), Inches(2.0), Inches(11.0), Inches(1.8))
    tf_t = title_box.text_frame
    tf_t.word_wrap = True
    p_t = tf_t.paragraphs[0]
    p_t.text = "Presentation Title Master"
    p_t.font.size = Pt(44)
    p_t.font.bold = True
    p_t.font.color.rgb = COLOR_TEXT_LIGHT

    # Subtitle Placeholder Textbox
    sub_box = slide_0.shapes.add_textbox(Inches(1.2), Inches(4.0), Inches(11.0), Inches(1.2))
    tf_s = sub_box.text_frame
    tf_s.word_wrap = True
    p_s = tf_s.paragraphs[0]
    p_s.text = "Subtitle or Key Takeaway Text"
    p_s.font.size = Pt(22)
    p_s.font.color.rgb = COLOR_TEAL_ACCENT

    # Footer
    foot_box = slide_0.shapes.add_textbox(Inches(0.8), Inches(6.6), Inches(11.7), Inches(0.4))
    tf_f = foot_box.text_frame
    p_f = tf_f.paragraphs[0]
    p_f.text = "Generated by MOTHER AI Presentation System • Confidential"
    p_f.font.size = Pt(9)
    p_f.font.color.rgb = COLOR_TEXT_MUTED

    # -------------------------------------------------------------------------
    # Layout 1: Title & Content Master Slide
    # -------------------------------------------------------------------------
    slide_layout_1 = prs.slide_layouts[1]
    slide_1 = prs.slides.add_slide(slide_layout_1)

    # Top accent header line
    top_line = slide_1.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(0.08))
    top_line.fill.solid()
    top_line.fill.fore_color.rgb = COLOR_TEAL_ACCENT
    top_line.line.fill.background()

    # Brand badge right top
    brand_box = slide_1.shapes.add_textbox(Inches(10.5), Inches(0.35), Inches(2.0), Inches(0.4))
    p_b = brand_box.text_frame.paragraphs[0]
    p_b.text = "MOTHER AI"
    p_b.alignment = PP_ALIGN.RIGHT
    p_b.font.size = Pt(10)
    p_b.font.bold = True
    p_b.font.color.rgb = COLOR_TEAL_ACCENT

    # Title Placeholder Textbox
    t1_box = slide_1.shapes.add_textbox(Inches(0.8), Inches(0.35), Inches(9.5), Inches(0.8))
    tf_t1 = t1_box.text_frame
    tf_t1.word_wrap = True
    p_t1 = tf_t1.paragraphs[0]
    p_t1.text = "Slide Header Title"
    p_t1.font.size = Pt(28)
    p_t1.font.bold = True
    p_t1.font.color.rgb = COLOR_TEXT_DARK

    # Content Container Card
    card_1 = slide_1.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.8), Inches(1.3), Inches(11.733), Inches(5.3))
    card_1.fill.solid()
    card_1.fill.fore_color.rgb = COLOR_LIGHT_BG
    card_1.line.color.rgb = COLOR_BORDER
    card_1.line.width = Pt(1)

    # Footer
    f1_box = slide_1.shapes.add_textbox(Inches(0.8), Inches(6.8), Inches(6.0), Inches(0.3))
    p_f1 = f1_box.text_frame.paragraphs[0]
    p_f1.text = "MOTHER Presentation Engine"
    p_f1.font.size = Pt(9)
    p_f1.font.color.rgb = COLOR_TEXT_MUTED

    # -------------------------------------------------------------------------
    # Layout 2: Two-Column Master Slide
    # -------------------------------------------------------------------------
    slide_layout_2 = prs.slide_layouts[2]
    slide_2 = prs.slides.add_slide(slide_layout_2)

    # Top accent header
    top_line2 = slide_2.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(13.333), Inches(0.08))
    top_line2.fill.solid()
    top_line2.fill.fore_color.rgb = COLOR_INDIGO_ACCENT
    top_line2.line.fill.background()

    # Title
    t2_box = slide_2.shapes.add_textbox(Inches(0.8), Inches(0.35), Inches(9.5), Inches(0.8))
    p_t2 = t2_box.text_frame.paragraphs[0]
    p_t2.text = "Two Column Comparison Title"
    p_t2.font.size = Pt(28)
    p_t2.font.bold = True
    p_t2.font.color.rgb = COLOR_TEXT_DARK

    # Left Column Card
    card_left = slide_2.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.8), Inches(1.3), Inches(5.7), Inches(5.3))
    card_left.fill.solid()
    card_left.fill.fore_color.rgb = COLOR_LIGHT_BG
    card_left.line.color.rgb = COLOR_BORDER
    card_left.line.width = Pt(1)

    # Right Column Card
    card_right = slide_2.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(6.833), Inches(1.3), Inches(5.7), Inches(5.3))
    card_right.fill.solid()
    card_right.fill.fore_color.rgb = COLOR_LIGHT_BG
    card_right.line.color.rgb = COLOR_BORDER
    card_right.line.width = Pt(1)

    # -------------------------------------------------------------------------
    # Save Presentation Template
    # -------------------------------------------------------------------------
    prs.save(str(out_file))
    print(f"[SUCCESS] Created Master PPT Template at: {out_file}")
    return str(out_file)


if __name__ == "__main__":
    out_path = sys.argv[1] if len(sys.argv) > 1 else "./templates/base_template.pptx"
    create_master_template(out_path)
