from __future__ import annotations

import os
import uuid
from pathlib import Path
from typing import Any, Optional
from pptx import Presentation
from backend.chats.presentation.planner import safe_filename

OUTPUT_DIR = Path(os.getenv("PPT_OUTPUT_DIR", "./outputs")).resolve()
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def save_presentation(prs: Presentation, title: str, presentation_id: Optional[str] = None, target_filename: Optional[str] = None) -> str:
    if target_filename:
        filename = target_filename
    elif presentation_id:
        filename = f"{presentation_id}.pptx"
    else:
        file_id = uuid.uuid4().hex
        filename = f"{safe_filename(title)}_{file_id}.pptx"

    file_path = OUTPUT_DIR / filename
    prs.save(str(file_path))
    return str(file_path)


def save_presentation_as_pdf(
    plan: Any,
    title: Optional[str] = None,
    presentation_id: Optional[str] = None,
    target_filename: Optional[str] = None,
) -> str:
    """Renders a 16:9 widescreen landscape presentation PDF using ReportLab with dynamic template styling."""
    from io import BytesIO
    from PIL import Image as PILImage
    from reportlab.lib.colors import HexColor
    from reportlab.lib.utils import ImageReader
    from reportlab.pdfgen import canvas
    import requests
    from backend.chats.presentation.scripts.templates import get_template_preset, to_hex_str
    from backend.chats.presentation.themes import get_theme_palette, is_light_color

    slide_title = getattr(plan, "title", None) or (plan.get("title") if isinstance(plan, dict) else None) or title or "Presentation"
    template_name = getattr(plan, "template_name", None) or (plan.get("template_name") if isinstance(plan, dict) else None)
    theme_attr = getattr(plan, "theme", None) or (plan.get("theme") if isinstance(plan, dict) else None)

    tmpl_cfg = get_template_preset(template_name) if template_name else {}
    if not tmpl_cfg and isinstance(theme_attr, str):
        tmpl_cfg = get_template_preset(theme_attr)

    if tmpl_cfg:
        bg_rgb = tmpl_cfg.get("bg")
        is_bg_light = is_light_color(bg_rgb) if hasattr(bg_rgb, "__getitem__") else False
        bg_hex = to_hex_str(tmpl_cfg.get("main_bg") or bg_rgb, "#0B0F19")
        accent_hex = to_hex_str(tmpl_cfg.get("accent"), "#38BDF8")
        accent_sec_hex = to_hex_str(tmpl_cfg.get("accent_sec"), accent_hex)
        text_hex = to_hex_str(tmpl_cfg.get("text_dark") if is_bg_light else tmpl_cfg.get("text_light"), "#FFFFFF" if not is_bg_light else "#0F172A")
        text_muted_hex = to_hex_str(tmpl_cfg.get("text_muted"), "#94A3B8")
        style_type = tmpl_cfg.get("style_type", "modern")
    else:
        palette = get_theme_palette(theme_attr or "midnight")
        bg_hex = to_hex_str(palette.get("background"), "#0B0F19")
        accent_hex = to_hex_str(palette.get("accent"), "#38BDF8")
        accent_sec_hex = to_hex_str(palette.get("badge"), accent_hex)
        text_hex = to_hex_str(palette.get("text"), "#FFFFFF")
        text_muted_hex = "#94A3B8"
        style_type = "modern"

    if target_filename:
        filename = target_filename if target_filename.endswith(".pdf") else f"{target_filename}.pdf"
    elif presentation_id:
        filename = f"{presentation_id}.pdf"
    else:
        file_id = uuid.uuid4().hex
        filename = f"{safe_filename(slide_title)}_{file_id}.pdf"

    file_path = OUTPUT_DIR / filename

    # Widescreen 16:9 canvas (960 x 540 points)
    width, height = 960.0, 540.0
    c = canvas.Canvas(str(file_path), pagesize=(width, height))

    slides = getattr(plan, "slides", []) or (plan.get("slides") if isinstance(plan, dict) else []) or []
    if not slides:
        slides = [{"title": slide_title, "subtitle": "Generated by Vitya Presentation Engine", "plugins": []}]

    for idx, slide in enumerate(slides):
        stitle = getattr(slide, "title", None) or (slide.get("title") if isinstance(slide, dict) else "") or f"Slide {idx + 1}"
        ssubtitle = getattr(slide, "subtitle", None) or (slide.get("subtitle") if isinstance(slide, dict) else "") or ""
        plugins = getattr(slide, "plugins", []) or (slide.get("plugins") if isinstance(slide, dict) else []) or []

        # 1. Background Fill according to selected template preset
        c.setFillColor(HexColor(bg_hex))
        c.rect(0, 0, width, height, fill=True, stroke=False)

        # 2. Dynamic Accent & Background Layout Decorators
        if style_type == "sidebar":
            c.setFillColor(HexColor(accent_hex))
            c.rect(0, 0, 45, height, fill=True, stroke=False)
        elif style_type == "berlin":
            c.setFillColor(HexColor(accent_hex))
            c.rect(0, height - 15, width, 15, fill=True, stroke=False)
        elif style_type == "quotable":
            c.setFillColor(HexColor(accent_hex))
            c.rect(0, height - 55, width, 55, fill=True, stroke=False)
        elif style_type == "crop":
            c.setFillColor(HexColor(accent_hex))
            c.rect(20, height - 30, 40, 4, fill=True, stroke=False)
            c.rect(20, height - 70, 4, 40, fill=True, stroke=False)
            c.rect(width - 60, 30, 40, 4, fill=True, stroke=False)
            c.rect(width - 24, 30, 4, 40, fill=True, stroke=False)
        elif style_type == "ion":
            c.setFillColor(HexColor(accent_hex))
            c.roundRect(width - 130, height - 35, 90, 20, 6, fill=True, stroke=False)
        else:
            c.setFillColor(HexColor(accent_hex))
            c.rect(40, height - 35, width - 80, 3, fill=True, stroke=False)

        # 3. Slide Title & Subtitle with contrast font color
        c.setFillColor(HexColor(text_hex))
        c.setFont("Helvetica-Bold", 22)
        c.drawString(60 if style_type == "sidebar" else 50, height - 70, str(stitle)[:75])

        curr_y = height - 95
        if ssubtitle:
            c.setFillColor(HexColor(text_muted_hex))
            c.setFont("Helvetica-Oblique", 13)
            c.drawString(60 if style_type == "sidebar" else 50, curr_y, str(ssubtitle)[:100])
            curr_y -= 25

        # 4. Plugins Rendering (Bullets, Paragraphs, Images, Cards)
        body_y = curr_y - 20
        c.setFont("Helvetica", 12)
        c.setFillColor(HexColor(text_hex))

        has_image = any((getattr(p, "type", None) or (p.get("type") if isinstance(p, dict) else "")) == "image" for p in plugins)
        max_text_width = 85 if not has_image else 50
        left_margin = 72 if style_type == "sidebar" else 55

        for p in plugins:
            p_type = getattr(p, "type", None) or (p.get("type") if isinstance(p, dict) else "")
            p_data = getattr(p, "data", None) or (p.get("data") if isinstance(p, dict) else {}) or {}

            if p_type == "bullets":
                items = p_data.get("items") or p_data.get("bullets") or []
                for item in items[:6]:
                    text = str(item) if not isinstance(item, dict) else item.get("text", "")
                    c.setFillColor(HexColor(accent_hex))
                    c.circle(left_margin + 3, body_y + 4, 3, fill=True, stroke=False)
                    c.setFillColor(HexColor(text_hex))
                    c.setFont("Helvetica", 13)
                    c.drawString(left_margin + 17, body_y, text[:max_text_width])
                    body_y -= 26

            elif p_type in ("paragraph", "text"):
                body_text = p_data.get("text") or p_data.get("content") or ""
                c.setFont("Helvetica", 12)
                c.setFillColor(HexColor(text_hex))
                words = str(body_text).split()
                line = ""
                for w in words:
                    if len(line + " " + w) > max_text_width:
                        c.drawString(left_margin, body_y, line.strip())
                        body_y -= 20
                        line = w
                    else:
                        line = f"{line} {w}"
                if line.strip():
                    c.drawString(left_margin, body_y, line.strip())
                    body_y -= 24

            elif p_type == "image":
                img_url = p_data.get("url") or p_data.get("path")
                if img_url and str(img_url).startswith("http"):
                    try:
                        resp = requests.get(img_url, timeout=3)
                        if resp.status_code == 200:
                            img_data = BytesIO(resp.content)
                            pil_img = PILImage.open(img_data)
                            img_reader = ImageReader(pil_img)
                            c.drawImage(img_reader, width - 380, height - 360, width=320, height=220, preserveAspectRatio=True)
                    except Exception:
                        pass

        # 5. Footer (Branding & Slide Page Number)
        c.setFillColor(HexColor(text_muted_hex))
        c.setFont("Helvetica", 10)
        c.drawString(60 if style_type == "sidebar" else 50, 25, f"{slide_title} • Vitya Presentation Deck")
        c.drawRightString(width - 50, 25, f"{idx + 1} / {len(slides)}")

        c.showPage()

    c.save()
    return str(file_path)


